  apiVersion: v1alpha1
  kind: AgentConfig
  metadata:
    name: openshift
  rendezvousIP: 10.0.11.2
  hosts:
    - hostname: master-0
      interfaces:
        - name: eno1
          macAddress: 52:54:00:15:cd:2f 
      rootDeviceHints:
        deviceName: /dev/sda
      networkConfig:
        interfaces:
          - name: eno1
            type: ethernet
            state: up
            mac-address: 52:54:00:15:cd:2f
            ipv4:
              enabled: true
              address:
                - ip: 10.0.11.2
                  prefix-length: 27
              dhcp: false
        dns-resolver:
          config:
            server:
              - 1.1.1.1 
        routes:
          config:
            - destination: 0.0.0.0/0
              next-hop-address: 10.0.11.30
              next-hop-interface: eno1
              table-id: 254
    - hostname: master-1
      interfaces:
        - name: eno1
          macAddress: 52:54:00:25:cd:2f
      rootDeviceHints:
        deviceName: /dev/sda
      networkConfig:
        interfaces:
          - name: eno1
            type: ethernet
            state: up
            mac-address: 52:54:00:25:cd:2f
            ipv4:
              enabled: true
              address:
                - ip: 10.0.11.3
                  prefix-length: 27
              dhcp: false
        dns-resolver:
          config:
            server:
              - 1.1.1.1
        routes:
          config:
            - destination: 0.0.0.0/0
              next-hop-address: 10.0.11.30
              next-hop-interface: eno1
              table-id: 254
    - hostname: master-2
      interfaces:
        - name: eno1
          macAddress: 52:54:00:35:cd:2f
      rootDeviceHints:
        deviceName: /dev/sda
      networkConfig:
        interfaces:
          - name: eno1
            type: ethernet
            state: up
            mac-address: 52:54:00:35:cd:2f
            ipv4:
              enabled: true
              address:
                - ip: 10.0.11.4
                  prefix-length: 27
              dhcp: false
        dns-resolver:
          config:
            server:
              - 1.1.1.1
        routes:
          config:
            - destination: 0.0.0.0/0
              next-hop-address: 10.0.11.30
              next-hop-interface: eno1
              table-id: 254
